# Generated by Django 3.2.20 on 2023-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_auto_20231213_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
